"""Core package for the HMM trading project."""

from hft_hmm._version import __version__
from hft_hmm.config import (
    EXPERIMENT_CONFIG_REFERENCE,
    DataSourceConfig,
    ExperimentConfig,
    compute_file_sha256,
    run_id,
)
from hft_hmm.core import (
    ALL_CATEGORIES,
    ENGINEERING_APPROXIMATION,
    EVALUATION_LAYER,
    PAPER_FAITHFUL,
    PaperReference,
    StateGrid,
    default_labels,
    linear_grid,
    module_category,
    reference,
)
from hft_hmm.data import (
    MarketDataSpec,
    MarketDataValidationError,
    load_csv_market_data,
    load_databento_parquet,
    load_yfinance_market_data,
    validate_market_data,
)
from hft_hmm.evaluation import (
    BACKTEST_METRICS_REFERENCE,
    apply_turnover_cost,
    cumulative_return,
    hit_rate,
    max_drawdown,
    sharpe_ratio,
    signal_turnover,
    summarize_backtest,
)
from hft_hmm.experiments import (
    WALK_FORWARD_REFERENCE,
    WalkForwardConfig,
    WalkForwardResult,
    WalkForwardWindow,
    walk_forward,
)
from hft_hmm.experiments.runner import NON_REPRODUCIBLE_WARNING, RunArtifacts, run_experiment
from hft_hmm.experiments.standalone_predictor import (
    STANDALONE_PREDICTOR_REFERENCE,
    StandaloneExperimentConfig,
    StandalonePredictorConfig,
    StandalonePredictorResult,
    StandalonePredictorWindow,
    StandaloneRunArtifacts,
    StandaloneWalkForwardConfig,
    run_standalone_experiment,
    standalone_predictor_backtest,
    standalone_run_id,
)
from hft_hmm.features import (
    DEFAULT_BUCKET_MINUTES,
    DEFAULT_EXCHANGE_TZ,
    INTRADAY_SEASONALITY_REFERENCE,
    VOLATILITY_RATIO_REFERENCE,
    SeasonalityConfig,
    VolatilityRatioConfig,
    ewma_volatility,
    intraday_seasonality,
    volatility_ratio,
)
from hft_hmm.inference import ForwardFilterResult, filter_from_result, forward_filter
from hft_hmm.models import (
    GaussianHMMResult,
    GaussianHMMWrapper,
    PLRBaselineResult,
    PLRSegment,
    PLRStateSummary,
    fit_piecewise_linear_regression,
)
from hft_hmm.preprocessing import compute_log_returns, resample_prices, train_test_split_time
from hft_hmm.project import PROJECT_NAME, ProjectInfo, get_project_info
from hft_hmm.selection import (
    ModelSelectionResult,
    ModelSelectionRow,
    aic,
    bic,
    compare_state_counts,
    count_gaussian_hmm_parameters,
    plot_selection_curves,
)
from hft_hmm.strategy import (
    SIGNAL_REFERENCE,
    align_signal_with_future_return,
    sign_signal,
    signal_from_filter_result,
    thresholded_signal,
)

__all__ = [
    "ALL_CATEGORIES",
    "BACKTEST_METRICS_REFERENCE",
    "DEFAULT_BUCKET_MINUTES",
    "DEFAULT_EXCHANGE_TZ",
    "ENGINEERING_APPROXIMATION",
    "EVALUATION_LAYER",
    "EXPERIMENT_CONFIG_REFERENCE",
    "INTRADAY_SEASONALITY_REFERENCE",
    "NON_REPRODUCIBLE_WARNING",
    "STANDALONE_PREDICTOR_REFERENCE",
    "StandaloneExperimentConfig",
    "StandalonePredictorConfig",
    "StandalonePredictorResult",
    "StandalonePredictorWindow",
    "StandaloneRunArtifacts",
    "StandaloneWalkForwardConfig",
    "PAPER_FAITHFUL",
    "PROJECT_NAME",
    "SIGNAL_REFERENCE",
    "VOLATILITY_RATIO_REFERENCE",
    "WALK_FORWARD_REFERENCE",
    "DataSourceConfig",
    "ExperimentConfig",
    "ForwardFilterResult",
    "GaussianHMMResult",
    "GaussianHMMWrapper",
    "MarketDataSpec",
    "MarketDataValidationError",
    "ModelSelectionResult",
    "ModelSelectionRow",
    "PaperReference",
    "PLRBaselineResult",
    "PLRSegment",
    "PLRStateSummary",
    "ProjectInfo",
    "RunArtifacts",
    "SeasonalityConfig",
    "StateGrid",
    "VolatilityRatioConfig",
    "WalkForwardConfig",
    "WalkForwardResult",
    "WalkForwardWindow",
    "__version__",
    "aic",
    "align_signal_with_future_return",
    "apply_turnover_cost",
    "bic",
    "compare_state_counts",
    "compute_file_sha256",
    "compute_log_returns",
    "count_gaussian_hmm_parameters",
    "cumulative_return",
    "default_labels",
    "ewma_volatility",
    "fit_piecewise_linear_regression",
    "filter_from_result",
    "forward_filter",
    "get_project_info",
    "hit_rate",
    "linear_grid",
    "load_csv_market_data",
    "load_databento_parquet",
    "load_yfinance_market_data",
    "max_drawdown",
    "module_category",
    "plot_selection_curves",
    "reference",
    "resample_prices",
    "run_experiment",
    "run_id",
    "run_standalone_experiment",
    "standalone_predictor_backtest",
    "standalone_run_id",
    "sharpe_ratio",
    "sign_signal",
    "signal_turnover",
    "signal_from_filter_result",
    "summarize_backtest",
    "thresholded_signal",
    "train_test_split_time",
    "intraday_seasonality",
    "validate_market_data",
    "volatility_ratio",
    "walk_forward",
]
